# Generated by Django 5.2.10 on 2026-01-14 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField()),
                ('poster_url', models.TextField()),
                ('trailers', models.JSONField(blank=True, default=dict)),
                ('genre', models.JSONField(blank=True, default=list)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('crew', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventtype')),
                ('languages', models.ManyToManyField(related_name='events', to='events.language')),
            ],
        ),
    ]
