# Generated by Django 5.2.10 on 2026-01-14 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
                ('state', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='ShowFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='infrastructure.city')),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_types', to='infrastructure.venue')),
            ],
            options={
                'verbose_name': 'Seat Type',
                'verbose_name_plural': 'Seat Types',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('seating_layout_template', models.JSONField()),
                ('total_capacity', models.IntegerField()),
                ('supported_formats', models.ManyToManyField(related_name='capable_screens', to='infrastructure.showformat')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screens', to='infrastructure.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.TextField()),
                ('seat_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='infrastructure.screen')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.seattype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('screen', 'row', 'seat_number'), name='unique_seat_per_screen')],
            },
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city', 'name'], name='infrastruct_city_id_db9176_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seattype',
            unique_together={('venue', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('venue', 'name')},
        ),
    ]
