# Generated by Django 5.2.10 on 2026-01-14 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='events.event')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='events.language')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='infrastructure.screen')),
                ('show_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.showformat')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='infrastructure.venue')),
            ],
        ),
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked'), ('blocked', 'Blocked')], db_index=True, default='available', max_length=20)),
                ('version', models.IntegerField(default=0)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='shows.show')),
            ],
        ),
        migrations.CreateModel(
            name='ShowSeatTypePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.seattype')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_config', to='shows.show')),
            ],
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['venue', 'show_datetime'], name='shows_show_venue_i_425ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['show', 'status'], name='shows_shows_show_id_154d0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='showseat',
            constraint=models.UniqueConstraint(fields=('show', 'seat'), name='unique_show_seat'),
        ),
        migrations.AddIndex(
            model_name='showseattypeprice',
            index=models.Index(fields=['show', 'seat_type'], name='shows_shows_show_id_7be8db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showseattypeprice',
            unique_together={('show', 'seat_type')},
        ),
    ]
