# Generated by Django 5.2.10 on 2026-01-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showseat',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
